### ISSUE TITLE
Upgrade elm-bootstrap to 4.0.0

### ISSUE THREAD

**Issue by StephenStrickland** [theNerd247/breeze-check#46]
For added functionality and features upgrade the package
`"rundis/elm-bootstrap": "3.0.0 <= v <= 4.0.0"`
This will break `ErrorMsg`, fix by using `simpleInfo` like so
```elm
errorView : Error -> Html Msg
errorView msg =
    Alert.simpleInfo []
        [ text msg.errorMsg
        , button [ class "close", onClick (CloseError msg.errorId) ] [ text "x" ]
        ]
```

**Comment by theNerd247** [comment]
done as of 2bdd89e248e05d92ebc8e911e521dbfd95b806cb
