### ISSUE TITLE
Implement Add Users Page

### ISSUE THREAD

**Issue by StephenStrickland** [theNerd247/breeze-check#49]
Use a bootstrap `ul` list for the form.
The last item of the `ul` will have an inline form to add a new Person.
The last name input box will can autocompletion feature that contains the Set of lastnames previously entered by the user. 
There should be a new address per distinct lastname entered in the above list. 
The user can assign the same address information for all, by clicking on a checkbox

**Comment by theNerd247** [comment]
done as of 6730463
